### ISSUE TITLE
Khovd (5984) is considered a coastal province.

### ISSUE THREAD

**Issue by Fahsfalu** [The-Triumvirate/Imperium-Universalis#315]
Its a province inside of the steppe far away from water
![20220419201848_1](https://user-images.githubusercontent.com/104041291/164121843-b4a8862d-0a0c-4ed9-a274-2fabd7133e56.jpg)
![20220419201852_1](https://user-images.githubusercontent.com/104041291/164121851-4c1fe7cc-94a5-424b-b8c8-01901e8efff0.jpg)
.
As the pictures show, the province can build ships despite being surrounded by land.

**Comment by billiamwill** [comment]
This is most likely because of a litteral 3 pixels of the wrong colour in provinces.bmp
![image](https://user-images.githubusercontent.com/107750034/174451824-27b992f0-8986-467e-9fa4-33145f87b17a.png)

![image](https://user-images.githubusercontent.com/107750034/174451860-cfcad91e-6886-421e-8218-7cd1889734e2.png)
