### ISSUE TITLE
Loading a save causes the Priesthood estate to lose 15 loyalty

### ISSUE THREAD

**Issue by AstridxV** [The-Triumvirate/Imperium-Universalis#317]
Playing a game as Egypt. Every time a save is loaded the Priesthood estate loses 15 loyalty, eventually reaching 0. Latest steam version, no submods.

**Comment by billiamwill** [comment]
You also gain 40 prestige, 100 legitimacy and 100 splendor on every game loaded, but you didn't complain about that, now did you ?

This stems from a wrong usage of flag "on_built = " in common\great_projects\monuments.txt.
on_built is triggered every time the game is loaded, because it's meant to update the map by adding the model for the great project. Vanilla eu4 only ever uses this flag like this:
on_built = {
	show_ambient_object = stpeters_cathedral
}

on_destroyed most likely works the same.

Those two should NEVER be used to add or substract resources. I guess the mod should use on_upgraded instead (and on_upgraded for tier_0 triggers when the project is destroyed, I believe)
