### ISSUE TITLE
Slaves owning most of the land out of the blue?

### ISSUE THREAD

**Issue by Krakna21** [The-Triumvirate/Imperium-Universalis#395]
![Screenshot (1236)](https://github.com/The-Triumvirate/Imperium-Universalis/assets/101092177/4a681751-f1f2-4135-9bb4-7a3faebe49fe)

**Comment by Krakna21** [comment]
![Screenshot (1237)](https://github.com/The-Triumvirate/Imperium-Universalis/assets/101092177/9fceb99b-0389-469c-b856-263129f3bdc4)

**Comment by Krakna21** [comment]
Happens every 5 years with the slave income event

**Comment by mrkcosta** [comment]
Those rascals! Hi, I'm the dev who did that
I reviewed it all again and I don't see where it could appear. I see that Slaves is the second estate in your screenshot, for any reason did nobility and merchants appear later? I don't know why you'd get anything with that, sorry. 
Still, I have "reinforced" the code regarding crownland so that any interaction forces -100% land share for slaves, for both sell and seize crownland.

**Comment by mrkcosta** [comment]
![imagen](https://github.com/The-Triumvirate/Imperium-Universalis/assets/5842997/732685a6-c6a2-4885-98a4-393d4504b8a7)
this decision you show is the Seize Crownland, instead of the Estates tab. It does show in the code that slaves will "disappear" with the -100%, although maybe it is due to being the last? Will do some checks on that

**Comment by mrkcosta** [comment]
![imagen](https://github.com/The-Triumvirate/Imperium-Universalis/assets/5842997/58369f45-6a5f-41b2-871a-17ebd44224ea)
Doing the same decision (without any of the modifications I am adding), it does show correctly!
So I'm sorry that I don't know where else to look for, but I will close this ticket. Thanks for reporting it! :)

**Comment by Krakna21** [comment]
> Those rascals! Hi, I'm the dev who did that I reviewed it all again and I don't see where it could appear. I see that Slaves is the second estate in your screenshot, for any reason did nobility and merchants appear later? I don't know why you'd get anything with that, sorry. Still, I have "reinforced" the code regarding crownland so that any interaction forces -100% land share for slaves, for both sell and seize crownland.

Yes, I also found it a little bit weird that slaves were the 2nd state on the list, which happened after forming the Makedonian kingdom via the mission tab, was taken 400 years before the above screenshot.

If helps, this anomaly happened entering midgame after my conquest of Gaul, had a massive amount of income (+5000), my population was about 20.000+ and my slave population was very low 2-3%

**Comment by mrkcosta** [comment]
Well then clearly I don't know what to say, nothing seems bad 👍 

The change of government with Makdedonian missions does not include any change for that:

if = {
	limit = {  
		government = tribal 
	}
	change_government = monarchy
	add_government_reform = aristocratic_monarchy_reform
}

Therefore, I close the ticket. Thanks for your feedback!
